site_name: BactoVision
site_description: A Jupyter widget for annotating and visualizing bacterial growth data
site_author: Vladimir Starostin
site_url: https://StarostinV.github.io/bactovision
repo_url: https://github.com/StarostinV/bactovision
repo_name: StarostinV/bactovision

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
      - Overview: user-guide/index.md
      - Basic Usage: user-guide/basic-usage.md
      - Grid: user-guide/grid.md
      - Annotation: user-guide/annotations.md
      - Metrics: user-guide/metrics.md
plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
      execute: false
      ignore_h1_titles: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/StarostinV/bactovision
