name: Build and Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger of the workflow

# Add permissions section for GitHub token
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install -e .

      - name: Deploy documentation
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: mkdocs gh-deploy --force 