name: Lint Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 flake8-docstrings
          pip install -e .

      - name: Check code formatting with Black
        run: black --check --diff bactovision tests

      - name: Check imports with isort
        run: isort --check --diff bactovision tests

      - name: Check code style with flake8
        run: flake8 bactovision tests 